spring:
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
#  main:
#    allow-bean-definition-overriding: true
  datasource:
#    url: jdbc:oracle:thin:@//your-local-ip-address:1521/TEST
    url: jdbc:oracle:thin:@//192.168.0.182:1521/TEST
#    url: jdbc:oracle:thin:@//192.168.56.1:1521/TEST
    username: tuser
    password: tpassword
    driverClassName: oracle.jdbc.driver.OracleDriver
    
    # ファイルサイズの合計の最大値
    # リクエストサイズの最大値
    # servlet:
    #   multipart: 
    #     max-file-size=1MB
    #     max-request-size=10MB
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true

    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
