spring:
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
#  main:
#    allow-bean-definition-overriding: true
  datasource:
#    url: jdbc:oracle:thin:@//your-local-ip-address:1521/TEST
    url: jdbc:oracle:thin:@//192.168.0.182:1521/TEST
    username: tuser
    password: tpassword
    driverClassName: oracle.jdbc.driver.OracleDriver
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
